config = YAML::load_file('config/application.yml')

:fog_credentials => {
  provider: 'AWS',
  region: 'Sydney',
  aws_access_key_id: ENV["S3_ACCESS_KEY"],
  aws_secret_access_key: ENV["S3_SECRET_KEY"]
}