development:
  stripe_publishable_key: ENV['STRIPE_PUBLISHABLE_KEY']
  stripe_secret_key: ENV['STRIPE_SECRET_KEY']

production:
  stripe_publishable_key: ENV['STRIPE_PUBLISHABLE_KEY']
  stripe_secret_key: ENV['STRIPE_SECRET_KEY']