development:
  stripe_publishable_key: <%=  ENV['PUBLISHABLE_KEY']%>
  stripe_secret_key: <%= ENV['SECRET_KEY']%>

production:
  stripe_publishable_key: <%= ENV['PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['SECRET_KEY']%>

